
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

public class GUI extends javax.swing.JFrame {
    
    ProblemStatement PS;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        PS = null;

        //Initialize Systemout Dump
        MessageConsole mc = new MessageConsole(SystemOut);
        mc.redirectOut(Color.green, System.out);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Doos = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        SystemOut = new javax.swing.JTextArea();
        NewWindow = new javax.swing.JCheckBox();
        AlgoSelector = new javax.swing.JComboBox<>();
        PackButton = new javax.swing.JButton();
        EvaluateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        Doos.setPreferredSize(new java.awt.Dimension(800, 800));
        Doos.setVisible(true);
        Doos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                DoosComponentResized(evt);
            }
        });

        javax.swing.GroupLayout DoosLayout = new javax.swing.GroupLayout(Doos.getContentPane());
        Doos.getContentPane().setLayout(DoosLayout);
        DoosLayout.setHorizontalGroup(
            DoosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        DoosLayout.setVerticalGroup(
            DoosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        SystemOut.setColumns(20);
        SystemOut.setRows(5);
        jScrollPane1.setViewportView(SystemOut);

        NewWindow.setText("Open in New window");

        AlgoSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatic Selection", "BackTrackCorner", "GreedyCorner", "GreedyTrivial", "MultipleGreedyCorner" }));
        AlgoSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgoSelectorActionPerformed(evt);
            }
        });

        PackButton.setText("Pack");
        PackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackButtonMouseClicked(evt);
            }
        });

        EvaluateButton.setText("Evaluate");
        EvaluateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EvaluateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Doos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EvaluateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlgoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewWindow))
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AlgoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(NewWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EvaluateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
            .addComponent(Doos, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DoosComponentResized

    }//GEN-LAST:event_DoosComponentResized

    private void AlgoSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgoSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlgoSelectorActionPerformed

    private void PackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackButtonMouseClicked
        PS = new ProblemStatement();
        if(!PS.fromFile()) return;
        
        PackerStrategy strategy = null;
        if (AlgoSelector.getSelectedItem() == "Automatic Selection") {
          System.out.println("Automatic Selection Chosen");
           strategy = (new StrategyPicker()).pick(PS);
        } else {
          System.out.println("Algorithm Selection Overriden");
          if (AlgoSelector.getSelectedItem() == "GreedyTrivial") {
              strategy = (new GreedyTrivialPack());
          }else if (AlgoSelector.getSelectedItem() == "BackTrackCorner") {
              strategy = (new BacktrackCornerPack());
          } else if (AlgoSelector.getSelectedItem() == "GreedyCorner") {
              strategy = (new GreedyCornerPack());
          } else if (AlgoSelector.getSelectedItem() == "MultipleGreedyCorner") {
              strategy = (new MultipleGreedyCornerPack());
          } else {
              System.out.println("No algorithm chosen to override");
              strategy = (new StrategyPicker()).pick(PS);
          }
        } 
        System.out.println("Applying " + strategy.getClass().getSimpleName());

        long startTime = System.currentTimeMillis();
        RectanglesContainer packedRC = strategy.pack(PS);
        long estimatedTime = System.currentTimeMillis() - startTime;
        System.out.println("Packing time : " + estimatedTime + "ms");

        PS.print();
        packedRC.printPlacement(PS.getRotationAllowed());
        visualize(packedRC);
        Doos.repaint();
    }//GEN-LAST:event_PackButtonMouseClicked

    private void EvaluateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluateButtonMouseClicked
        PS = new ProblemStatement();
        if(!PS.fromFile()) return;
        
        PackerStrategy strategy = null;
        if (AlgoSelector.getSelectedItem() == "Automatic Selection") {
          System.out.println("Automatic Selection Chosen");
           strategy = (new StrategyPicker()).pick(PS);
        } else {
          System.out.println("Algorithm Selection Overriden");
          if (AlgoSelector.getSelectedItem() == "GreedyTrivial") {
              strategy = (new GreedyTrivialPack());
          }else if (AlgoSelector.getSelectedItem() == "BackTrackCorner") {
              strategy = (new BacktrackCornerPack());
          } else if (AlgoSelector.getSelectedItem() == "GreedyCorner") {
              strategy = (new GreedyCornerPack());
          } else if (AlgoSelector.getSelectedItem() == "MultipleGreedyCorner") {
              strategy = (new MultipleGreedyCornerPack());
          } else {
              System.out.println("No algorithm chosen to override");
              strategy = (new StrategyPicker()).pick(PS);
          }
        } 
        System.out.println("Applying " + strategy.getClass().getSimpleName());
       
        Evaluator E = new Evaluator();
        Evaluation eval = E.Evaluate(strategy, PS, 10);
        System.out.println(eval.t+","+eval.fr);
    }//GEN-LAST:event_EvaluateButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlgoSelector;
    private javax.swing.JInternalFrame Doos;
    private javax.swing.JButton EvaluateButton;
    private javax.swing.JCheckBox NewWindow;
    private javax.swing.JButton PackButton;
    private javax.swing.JTextArea SystemOut;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void visualize(RectanglesContainer packedRC) {

        int windowSizeX = 700;
        int windowSizeY = 700;

        int maxx = packedRC.getBoundingWidth();
        int maxy = packedRC.getBoundingHeight();

        if (maxx == 0 || maxy == 0) {
            return;
        }

        float scale = maxx >= maxy ? (float) windowSizeX / maxx : (float) windowSizeY / maxy;

        //create an image and its graphics 
        BufferedImage image = packedRC.visualize();

        //create window
        JFrame Doos2 = new JFrame();
        Doos.setTitle("  Bounding Dimensions : " + packedRC.getBoundingWidth() + "," + packedRC.getBoundingHeight()
                + ", Bounding Area : " + packedRC.getBoundingArea()
                + ", Rectangles Area :" + packedRC.getRectanglesArea()
                + ", Cost : " + packedRC.getCost());

        Doos.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Doos.setSize(windowSizeX + 16, windowSizeY + 39);//+16,+40 for windows bullshit

        JPanel paintBox = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, (int) (maxx * scale), (int) (maxy * scale), 0, 0, maxx, maxy, null);
            }
        };
        Doos2.getContentPane().add(paintBox);
        if (NewWindow.isSelected()) {
            Doos2.setSize(windowSizeX + 16, windowSizeY + 39);//+16,+40 for windows bullshit
            Doos2.setTitle("  Bounding Dimensions : " + packedRC.getBoundingWidth() + "," + packedRC.getBoundingHeight()
                + ", Bounding Area : " + packedRC.getBoundingArea()
                + ", Rectangles Area :" + packedRC.getRectanglesArea()
                + ", Cost : " + packedRC.getCost());
            Doos2.setVisible(true);
        } else {
        Doos.setContentPane(Doos2.getContentPane());
        paintBox.setVisible(true);
        }
    }
}
